### ISSUE TITLE
Seen using wrong names

### ISSUE THREAD

**Issue by cruxicheiros** [CraftSpider/TalosBot#26]
Welcome to PtP, Dino! 7:17

Dino: ^seen Dino 7:17

Talos [Bot]: User Dino was last seen 10:17 7:17

Dino: ^seen sdfghjkl; 7:17

Dino: ...oh 7:17

Dino: hmm 7:17

Dino: (I need to leave in 5 min) 7:18

Dino: ^seen Lily 7:18

Talos [Bot]: User sdfghjkl; was last seen May 15 7:18

Dino: -_- 7:18

Dino: ^seen Lily 7:18

Talos [Bot]: User Lily was last seen May 15 7:18

Dino: -_______- 7:18

Dino: ^seen notarealuser 7:19

Dino: ^seen Dino 7:19

Talos [Bot]: I couldn't find notarealuser. Sorry. 7:19

Dino: ah ok 7:19

Dino: k 7:19

Dino: done testing. ttyl guys. 7:19

Elluna: ^seen HELLuna 7:20

Talos [Bot]: User Dino was last seen Oct 31 7:20

Elluna: o_o 7:21

Elluna: I AM NOT DINO 7:21

Elluna: ^seen jas 7:21

Talos [Bot]: User jas was last seen Nov 10 7:21

HawthornShadow: Calm, 'Llu

**Comment by CraftSpider** [comment]
I... think I know what's wrong, but I'm still working on how to fix it

**Comment by CraftSpider** [comment]
This should be fixed now

**Comment by CraftSpider** [comment]
Gonna close this, as Seen is now acting stably. For the first time in ever.
