### ISSUE TITLE
writingHour

### ISSUE THREAD

**Issue by CraftSpider** [CraftSpider/TalosBot#3]
Writing hour function closes chat, but on a loop. For the rest of the minute until the minute passes. Maybe make a boolean to flip for each of the three alerts, then reset it after WH ends?

**Comment by cruxicheiros** [comment]
I made the time it goes off on more specific, which fixed the problem.

**Comment by CraftSpider** [comment]
What if the bot is delayed by running a command over that second?

**Comment by CraftSpider** [comment]
Attempted to fix the problem in the utility branch, needs testing

**Comment by CraftSpider** [comment]
Tested and proven to work
