### ISSUE TITLE
Rapid posts not going through

### ISSUE THREAD

**Issue by CraftSpider** [CraftSpider/TalosBot#43]
When Talos tries to post multiple things in quick succession, only some will end up actually going out. Figure out how to fix this?

**Comment by SerraraFluttershy** [comment]
Hmm....may I see the code snippet which handles Talos doing so?
I feel like this is an issue of timing more than anything else.

**Comment by CraftSpider** [comment]
That was my guess. The relevant code is actually probably in the ChatzyAPI repo, in postMessage
