### ISSUE TITLE
WordWar ideas

### ISSUE THREAD

**Issue by CraftSpider** [CraftSpider/TalosBot#5]
A) Add keys so that WWs are distinguishable
B) Max number of WWs at once
C) WordWars start at a given time

**Comment by cruxicheiros** [comment]
A) has been solved and is functional; B and C have not been started.

**Comment by CraftSpider** [comment]
B has been added to the utility branch, I tested it a bit and it seems to work okay.

**Comment by CraftSpider** [comment]
B is done, C is being worked on

**Comment by CraftSpider** [comment]
C needs final review, but should work now.

**Comment by CraftSpider** [comment]
C is effectively tested. I declare these goals achieved.
