### ISSUE TITLE
Nano profile website link doesn't work

### ISSUE THREAD

**Issue by thecoloryes** [CraftSpider/TalosBot#56]
`^nanowrimo profile thecolouryes`
![image](https://user-images.githubusercontent.com/1203116/46827060-a517ee00-cd65-11e8-87e1-c66027ad6791.png)
on nano site:
![image](https://user-images.githubusercontent.com/1203116/46827078-acd79280-cd65-11e8-9a60-c8b58c87629a.png)

**Comment by CraftSpider** [comment]
Fixed in new version, wasn't accounting for the <a> element
