### ISSUE TITLE
Help ideas

### ISSUE THREAD

**Issue by CraftSpider** [CraftSpider/TalosBot#8]
A) Add ^help [Command] functions, to describe commands possible arguments.
B) Maybe make ^[Command] help do the same thing, maybe just re-route to ^help [Command]?

**Comment by CraftSpider** [comment]
A is partially done, still need to fill out descriptions.

**Comment by cruxicheiros** [comment]
B clashes with WW, which takes a keyword. Not sure if it should be implemented.

**Comment by CraftSpider** [comment]
A still needs descriptions, B isn't being done now

**Comment by CraftSpider** [comment]
Descriptions now fleshed out. Closing this one up.
